### ISSUE TITLE
Can you add a FileTimeRotationPolicy(3600, Units.SECONDS);

### ISSUE THREAD

**Issue by evidanary** [ptgoetz/storm-hdfs#10]
I want to rotate the file every 10 minutes regardless of the size. The rotated file will land in a HIVE table directory. This way I can have an SLA for data liveness when someone queries a hive table.

FileTimeRotationPolicy(600, Units.SECONDS);  //For 10 minutes
FileTimeRotationPolicy(60, Units.MINUTES);  //For One Hour

**Comment by ptgoetz** [comment]
Added ability to rotate on time intervals.
