### ISSUE TITLE
Is there a way I can compress the output file to HDFS? Trident state. withCompression(true,codec)?

### ISSUE THREAD

**Issue by xelllee** [ptgoetz/storm-hdfs#2]
I remember I had issue with compressionOutputStream's sync/flush. it was not working well. Is this related?

  HdfsState.Options options = new HdfsState.Options()
                 .withFileNameFormat(fileNameFormat)
                 .withRecordFormat(recordFormat)
                 .withRotationPolicy(rotationPolicy)
                 .withFsUrl("hdfs://localhost:54310")
                 .withPath("/trident");
                 .withCompression(true,codec)?

**Comment by ptgoetz** [comment]
The storm-hdfs Trident API doesn't support sequence files or compression yet. But will be added in the very near future (days).

The bolt implementation supports compressed sequence files. Just make sure you have the right native libraries installed to the compression codec you choose if it's not `deflate` or `default`.

**Comment by xelllee** [comment]
Perfect, Thanks  Looking forward to. :)
