### ISSUE TITLE
 java.lang.NoSuchMethodError: org.apache.hadoop.fs.FSOutputSummer.<init>(Ljava/util/zip/Checksum;II)V

### ISSUE THREAD

**Issue by 2vinodhkumar** [ptgoetz/storm-hdfs#24]
Hi, When I am running HDFS Bolt either on Cluster(Hortonworks or Own) or in Localcluster mode I am getting the same error , creats hdfs files but doesn't write any data.

java.lang.NoSuchMethodError: org.apache.hadoop.fs.FSOutputSummer.<init>(Ljava/util/zip/Checksum;II)V

**Comment by 2vinodhkumar** [comment]
While Running in LocalCluster mode on console It is also giving a warning like native-hadoop library not found

**Comment by 2vinodhkumar** [comment]
Resolved this, My hadoop cluster is 2.6.0 but I am using hadoop-hdfs-2.2.0 in replaced it with 2.6.0 now it is working fine

**Comment by 1jacky** [comment]
hbase    hadoop-hdfs-2.5.1.jar , but your cluster is   hadoop-hdfs-2.6.2.jar  replace hbase/lib/ hadoop-hdfs-2.5.1.jar
