### ISSUE TITLE
Write to HDFS hive partition.

### ISSUE THREAD

**Issue by xelllee** [ptgoetz/storm-hdfs#3]
In HdfsState.java, would you please add a way to config to write dynamic path.
I need this to write to hdfs hive partition by day. 

It is like 
drwxr-xr-x   - hdfs tbuser          0 2013-11-18 23:20 /staging/anvil/processed/parsed/access/dc=2013-11-18
drwxr-xr-x   - hdfs tbuser          0 2013-11-19 23:15 /staging/anvil/processed/parsed/access/dc=2013-11-19
drwxr-xr-x   - hdfs tbuser          0 2013-11-20 11:31 /staging/anvil/processed/parsed/access/dc=2013-11-20

Thanks

HdfsState.Options options = new HdfsState.Options()
                 .withFileNameFormat(fileNameFormat)
                 .withRecordFormat(recordFormat)
                 .withRotationPolicy(rotationPolicy)
                 .withFsUrl("hdfs://localhost:54310")
                 .withPath(path);

**Comment by ptgoetz** [comment]
Can you provide some clarification?

What is your use case? The bolt provides a way to register listeners for when file rotation occurs (allowing you to move, etc. a file).

Are you looking for the same functionality in the trident implementation, or something else?

**Comment by xelllee** [comment]
I haven't looked at the listener yet. basically,  I have a hive table partitioned by date, on Hdfs it looks like 
/staging/anvil/processed/parsed/access/dc=2013-11-20/

"dc=2013-11-20" is the partition directory created every day.

With the lib, I am able to pass the static path.  

HdfsState.Options options = new HdfsState.Options()
....
.withPath("/staging/anvil/processed/parsed/access/");

but "dc=2014-02-06" is dynamic. For example, Today HdfsState needs to write to '/staging/anvil/processed/parsed/access/dc=2014-02-06/', 
but tomorrow would be 
'/staging/anvil/processed/parsed/access/dc=2014-02-07/'

Is the listener i should look into ?

Thanks

**Comment by ptgoetz** [comment]
Okay, I added support for sequence files to the Trident State implementation, as well as support for `RotationAction`s.

What `RotationAction`s do is provide a hook to allow you to perform some action right after a file is rotated. For example, moving a file to a different location or renaming it.

There's a simple move action included that will move a file right after rotation:

``` java
public class MoveFileAction implements RotationAction {
    private static final Logger LOG = LoggerFactory.getLogger(MoveFileAction.class);

    private String destination;


    public MoveFileAction withDestination(String destDir){
        destination = destDir;
        return this;
    }

    @Override
    public void execute(FileSystem fileSystem, Path filePath) throws IOException {
        Path destPath = new Path(destination, filePath.getName());
        LOG.info("Moving file {} to {}", filePath, destPath);
        boolean success = fileSystem.rename(filePath, destPath);
        return;
    }
}
```

So if you are using Trident and sequence files you can do something like this:

``` java
        HdfsState.Options seqOpts = new HdfsState.SequenceFileOptions()
                .withFileNameFormat(fileNameFormat)
                .withSequenceFormat(new DefaultSequenceFormat("key", "data"))
                .withRotationPolicy(rotationPolicy)
                .withFsUrl("hdfs://localhost:54310")
                .withPath("/trident")
                .addRotationAction(new MoveFileAction().withDestination("/dest2/"));
```

If that doesn't work for your use case, let me know and we can probably change the API to get you what you need.

**Comment by xelllee** [comment]
that will do, thanks

**Comment by rs-01** [comment]
I have similar use case where data needs to be saved in a directory created by using values from the message being processed. My use case requires partitioning data by timestamp of the event. Events in the pipeline can get delayed by several hours or days. Pipeline gets events that occurred few seconds ago to few days. I need to save these events in different directories based on their timestamp. I am looking for some way of doing it in Trident implementation.

**Comment by fescandell** [comment]
@rs-01 : I have almost the same problem, did you solve it?
