### ISSUE TITLE
MapReduce reads file currently being written to by "Storm-hdfs".

### ISSUE THREAD

**Issue by xelllee** [ptgoetz/storm-hdfs#7]
While the file is open for appending by the bolt, you could "hadoop fs -cat /file" to see the content whenever the hsync is called by the bolt, but the size of the file shows "0". 

when you do mapreduce job hive query on the file, the file is not visible to the the hadoop job until it is closed (when bolt does the rotation)

What could be done to make it available to Hadoop job while it is being appended.?

**Comment by evidanary** [comment]
@xelllee I'm seeing the same thing. Is this issue resolved in the latest commit?

**Comment by xelllee** [comment]
Probably no, I close the file more frequently. And merge the small files afterwards. 

Any good idea ?

**Comment by evidanary** [comment]
@xelllee That's what I'm doing. The only problem is that if the topology is killed while it is writing to the landing file then all changes are lost. Only rotated files have data in them. Are you seeing the same thing?

**Comment by xelllee** [comment]
You could try to do more hsync.

**Comment by ptgoetz** [comment]
I am looking into this and hope to have a solution soon.

**Comment by sureshms** [comment]
HDFS hsync ensures that the bolt flushes the data in the buffer to the pipeline of datanodes it is writing to. The datanodes also fsyncs the data to the disk. This ensures durability guarantee. But the file length at the namenode will not see the length corresponding to hsync.

There are two alternatives that readers can do to read the hsynced data:
1. A reader can get the current length from the stream that is returned for reading using HdfsDataInputStream#getVisibleLength(). See some examples in HDFS tests - TestReadWhileWriting.java, TestWriteRead.java
2. Writer can update the NameNode with the file length using the call HdfsDataInputStream#hsync(EnumSet.of(SyncFlag.UPDATE_LENGTH)) along with the other hsync functionality. This is more expensive.

I think HDFS cat command currently does not use visible length for reads.

Hope this helps.

**Comment by ptgoetz** [comment]
@sureshms, Thank for the in depth explanation. I will update accordingly (#2).

**Comment by ptgoetz** [comment]
Fixed.
