### ISSUE TITLE
DelimitedRecordFormat fails to write appropriate fields to hdfs

### ISSUE THREAD

**Issue by sheetaldolas** [ptgoetz/storm-hdfs#9]
DelimitedRecordFormat works only when all fields in tuple are written in the order they are emitted. (or only first field is to be written to HDFS). Writing selective fields from tuple does not work always.

Attached is patch

diff --git a/src/main/java/org/apache/storm/hdfs/bolt/format/DelimitedRecordFormat.java b/src/main/java/org/apache/storm/hdfs/bolt/format/DelimitedRecordFormat.java
index e7137e5..2bd3abb 100644
--- a/src/main/java/org/apache/storm/hdfs/bolt/format/DelimitedRecordFormat.java
+++ b/src/main/java/org/apache/storm/hdfs/bolt/format/DelimitedRecordFormat.java
@@ -77,7 +77,7 @@
         Fields fields = this.fields == null ? tuple.getFields() : this.fields;
         int size = fields.size();
         for(int i = 0; i < size; i++){
-            sb.append(tuple.getValue(i));
-            sb.append(tuple.getValueByField(fields.get(i)));
           if(i != size - 1){
               sb.append(this.fieldDelimiter);
           }

**Comment by ptgoetz** [comment]
Done.
